services:
  echo:
    baseUrl: http://127.0.0.1:8089
    enabled: true
    host: 0.0.0.0
    port: 8089
  echoScheduler:
    baseUrl: http://127.0.0.1:8089
    enabled: false
    host: 0.0.0.0
    port: 8089
  echoWorker:
    baseUrl: http://127.0.0.1:8089
    enabled: false
    host: 0.0.0.0
    port: 8089

gitlabci:
  enabled: true
  masters:
    - address: "https://git.redbox.com"
      name: redbox
      privateToken: ${PRIVATE_TOKEN}
